celebrities = [
    {"name": "Taylor Swift", "followers": 250000000, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Cristiano Ronaldo", "followers": 400000000, "description": "Professional footballer", "country": "Portugal"},
    {"name": "Ariana Grande", "followers": 220000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Dwayne Johnson", "followers": 290000000, "description": "Actor and former wrestler", "country": "USA"},
    {"name": "Selena Gomez", "followers": 200000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Kylie Jenner", "followers": 230000000, "description": "Media personality and businesswoman", "country": "USA"},
    {"name": "Lionel Messi", "followers": 300000000, "description": "Professional footballer", "country": "Argentina"},
    {"name": "Kim Kardashian", "followers": 240000000, "description": "Media personality and businesswoman", "country": "USA"},
    {"name": "Beyoncé", "followers": 210000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Neymar Jr.", "followers": 250000000, "description": "Professional footballer", "country": "Brazil"},
    {"name": "Justin Bieber", "followers": 210000000, "description": "Singer and songwriter", "country": "Canada"},
    {"name": "Billie Eilish", "followers": 150000000, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Kanye West", "followers": 120000000, "description": "Rapper and producer", "country": "USA"},
    {"name": "Shakira", "followers": 170000000, "description": "Singer and songwriter", "country": "Colombia"},
    {"name": "Rihanna", "followers": 220000000, "description": "Singer and businesswoman", "country": "Barbados"},
    {"name": "Drake", "followers": 180000000, "description": "Rapper and singer", "country": "Canada"},
    {"name": "Jennifer Lopez", "followers": 160000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Emma Watson", "followers": 100000000, "description": "Actress and activist", "country": "UK"},
    {"name": "LeBron James", "followers": 120000000, "description": "Professional basketball player", "country": "USA"},
    {"name": "David Beckham", "followers": 130000000, "description": "Former professional footballer", "country": "UK"},
    {"name": "Shawn Mendes", "followers": 100000000, "description": "Singer and songwriter", "country": "Canada"},
    {"name": "Zendaya", "followers": 110000000, "description": "Actress and singer", "country": "USA"},
    {"name": "Chris Hemsworth", "followers": 90000000, "description": "Actor", "country": "Australia"},
    {"name": "Gal Gadot", "followers": 80000000, "description": "Actress and model", "country": "Israel"},
    {"name": "Miley Cyrus", "followers": 100000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Vin Diesel", "followers": 70000000, "description": "Actor and producer", "country": "USA"},
    {"name": "Gigi Hadid", "followers": 70000000, "description": "Model", "country": "USA"},
    {"name": "Cardi B", "followers": 90000000, "description": "Rapper and songwriter", "country": "USA"},
    {"name": "Kendall Jenner", "followers": 120000000, "description": "Model and media personality", "country": "USA"},
    {"name": "Priyanka Chopra", "followers": 70000000, "description": "Actress and singer", "country": "India"},
    {"name": "Ellen DeGeneres", "followers": 80000000, "description": "Comedian and TV host", "country": "USA"},
    {"name": "Tom Holland", "followers": 70000000, "description": "Actor", "country": "UK"},
    {"name": "Ed Sheeran", "followers": 100000000, "description": "Singer and songwriter", "country": "UK"},
    {"name": "Kourtney Kardashian", "followers": 90000000, "description": "Media personality and businesswoman", "country": "USA"},
    {"name": "Will Smith", "followers": 50000000, "description": "Actor and rapper", "country": "USA"},
    {"name": "Demi Lovato", "followers": 90000000, "description": "Singer and actress", "country": "USA"},
    {"name": "Sophie Turner", "followers": 15000000, "description": "Actress", "country": "UK"},
    {"name": "Hugh Jackman", "followers": 30000000, "description": "Actor and producer", "country": "Australia"},
    {"name": "Margot Robbie", "followers": 20000000, "description": "Actress and producer", "country": "Australia"},
    {"name": "Blake Lively", "followers": 30000000, "description": "Actress", "country": "USA"},
    {"name": "Robert Downey Jr.", "followers": 50000000, "description": "Actor and producer", "country": "USA"},
    {"name": "Katy Perry", "followers": 100000000, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Jason Momoa", "followers": 15000000, "description": "Actor and producer", "country": "USA"},
    {"name": "Keanu Reeves", "followers": 20000000, "description": "Actor and musician", "country": "Canada"},
    {"name": "Gal Gadot", "followers": 60000000, "description": "Actress and model", "country": "Israel"},
    {"name": "Chris Evans", "followers": 90000000, "description": "Actor", "country": "USA"},
    {"name": "Liam Hemsworth", "followers": 13000000, "description": "Actor", "country": "Australia"},
    {"name": "Brie Larson", "followers": 10000000, "description": "Actress and filmmaker", "country": "USA"},
    {"name": "Tom Hiddleston", "followers": 8000000, "description": "Actor", "country": "UK"},
    {"name": "Natalie Portman", "followers": 7000000, "description": "Actress and filmmaker", "country": "USA"},
    {"name": "Daniel Radcliffe", "followers": 5000000, "description": "Actor", "country": "UK"},
    {"name": "Emma Stone", "followers": 3000000, "description": "Actress", "country": "USA"},
    {"name": "Alicia Vikander", "followers": 1000000, "description": "Actress", "country": "Sweden"},
    {"name": "Saoirse Ronan", "followers": 2000000, "description": "Actress", "country": "Ireland"},
    {"name": "Timothée Chalamet", "followers": 8000000, "description": "Actor", "country": "USA"},
    {"name": "Florence Pugh", "followers": 4000000, "description": "Actress", "country": "UK"},
    {"name": "Zendaya", "followers": 110000000, "description": "Actress and singer", "country": "USA"},
    {"name": "Millie Bobby Brown", "followers": 30000000, "description": "Actress", "country": "UK"},
    {"name": "Henry Cavill", "followers": 17000000, "description": "Actor", "country": "UK"},
    {"name": "Idris Elba", "followers": 10000000, "description": "Actor and musician", "country": "UK"},
    {"name": "Gal Gadot", "followers": 60000000, "description": "Actress and model", "country": "Israel"},
    {"name": "Ryan Reynolds", "followers": 30000000, "description": "Actor and producer", "country": "Canada"}
]